package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author munazir
 */
public class AddDoctor extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AddDoctor() {
        initComponents();
        setLocationRelativeTo(null);
        resetValues();

        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tfContact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comDepart = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comHospital = new javax.swing.JComboBox<>();
        tfDname = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 600));
        setPreferredSize(new java.awt.Dimension(1300, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(190, 235, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Doctors");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 430, 60));

        jPanel2.setBackground(new java.awt.Color(153, 183, 190));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 54, -1, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Username", "Password", "Gender", "Contact", "Department", "Hospital"
            }
        ));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 690, 270));

        jPanel4.setBackground(new java.awt.Color(190, 235, 200));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Doctors List");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 200, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 690, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        tfPass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 290, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Doctor name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 30));

        tfuser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(tfuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Gender");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        buttonGroup1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        jPanel2.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 120, 30));

        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rbFemale.setText("Female");
        jPanel2.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Contact");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 20));

        tfContact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContactActionPerformed(evt);
            }
        });
        jPanel2.add(tfContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 290, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Department");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        comDepart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Medicine", "Surgery", "Diabetes", "neurology", "Dental", "Unani Medicine", "urology", " ", " " }));
        jPanel2.add(comDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 290, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Hospital");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        comHospital.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "LABAID", "DMC", "IBSINA", "BIRDEM", "CMH", "CENTRAL HOSPITAl" }));
        jPanel2.add(comHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 290, 30));

        tfDname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(tfDname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 290, 30));

        Addbtn.setBackground(new java.awt.Color(153, 183, 190));
        Addbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 70, -1));

        Updatebtn.setBackground(new java.awt.Color(153, 183, 190));
        Updatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        jPanel2.add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        Deletebtn.setBackground(new java.awt.Color(153, 183, 190));
        Deletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        jPanel2.add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, -1, -1));

        Exitbtn.setBackground(new java.awt.Color(153, 183, 190));
        Exitbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logout.png"))); // NOI18N
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 500, 76, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:

        String fullname = tfDname.getText();
        String name = tfuser.getText();
        String pass = tfPass.getText();
        String gender = "";
        if (rbMale.isSelected()) {
            gender = "male";
        } else if (rbFemale.isSelected()) {
            gender = "female";
        }

        String age = tfContact.getText();
        String contact = comDepart.getSelectedItem().toString();
        String address = comHospital.getSelectedItem().toString();
        String userrole = "doctor";

        UserModel user = new UserModel(fullname, name, pass, userrole, gender, age, contact, address);

        if (validated(user)) {
            try {
                String sql = " insert into login_table(fullname,username,password,userrole,gender,age,contact,address) values(?,?,?,?,?,?,?,?)";

                Connection conn = DBConnector.getConnection();

                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, fullname);
                ps.setString(2, name);
                ps.setString(3, pass);
                ps.setString(4, userrole);
                ps.setString(5, gender);
                ps.setString(6, age);
                ps.setString(7, contact);
                ps.setString(8, address);
                ps.execute();
                System.out.println("Added Success");
                resetValues();
                loadTable();

                // dispose();
                // new Login().setVisible(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }


    }//GEN-LAST:event_AddbtnActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void resetValues() {
        tfDname.setText(null);
        tfuser.setText(null);
        tfPass.setText(null);
        rbMale.setSelected(false);
        rbFemale.setSelected(false);
        tfContact.setText(null);
        comDepart.setSelectedIndex(0);
        comHospital.setSelectedIndex(0);

    }


    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:

        update();
        resetValues();


    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        // TODO add your handling code here:

        //int selectedRow = dataTable.getSelectedRow();
        // dataTable.getValueAt(selectedRow, 0);
        int selectedRow = dataTable.getSelectedRow();
        String fullname = (String) dataTable.getValueAt(selectedRow, 0);
        String name = (String) dataTable.getValueAt(selectedRow, 1);
        String pass = (String) dataTable.getValueAt(selectedRow, 2);
        String gender = (String) dataTable.getValueAt(selectedRow, 3);
        String age = (String) dataTable.getValueAt(selectedRow, 4);
        String contact = (String) dataTable.getValueAt(selectedRow, 5);
        String address = (String) dataTable.getValueAt(selectedRow, 6);

        tfDname.setText(fullname);
        tfuser.setText(name);
        tfPass.setText(pass);
        rbMale.setSelected(false);
        rbFemale.setSelected(false);
        tfContact.setText(age);
        comDepart.setSelectedIndex(0);
        comHospital.setSelectedIndex(0);


    }//GEN-LAST:event_dataTableMouseClicked

    private void update() {
        try {

            String fullname = tfDname.getText();
            String name = tfuser.getText();
            String pass = tfPass.getText();

            String age = tfContact.getText();
            String contact = comDepart.getSelectedItem().toString();
            String address = comHospital.getSelectedItem().toString();

            //String address = comDepart.setSelectedIndex(0);
            //String userrole = "doctor";
            Connection conn = DBConnector.getConnection();

            String sql = "update login_table set fullname = ?,  password =? ,age= ?, contact = ?,address = ? where username = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, fullname);
         
            pst.setString(2, pass);
            pst.setString(3, age);
            pst.setString(4, contact);
            pst.setString(5, address);
            pst.setString(6, name);

            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(rootPane, "updated Successfully");
                loadTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "updated failed");
            }
            resetValues();
            loadTable();
          

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }


    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
            String name = tfDname.getText();
            Connection conn = DBConnector.getConnection();
            String sql = "DELETE FROM login_table WHERE fullname=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, (name));
            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(rootPane, "Delete Successfully");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deleted Failed");
            }
            loadTable();
            resetValues();
        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_DeletebtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:

        dispose();
        new Admin().setVisible(true);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void tfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comDepart;
    private javax.swing.JComboBox<String> comHospital;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfContact;
    private javax.swing.JTextField tfDname;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables

    private boolean validated(UserModel user) {
        boolean isValid = true;
        String msg = "";

      

        

        if (!user.getUsername().matches("[a-zA-Z]+")) {
            isValid = false;
            msg += "User Name Not valid\n";

        }
        if (!user.getPassword().matches("[0-9]+")) {
            isValid = false;
            msg += "Pass Word Not valid\n";

        }

        if (!user.getGender().matches("[a-zA-Z]+")) {
            isValid = false;
            msg += "Gender Not valid\n";

        }

        if (!isValid) {
            JOptionPane.showMessageDialog(null, msg);
        }

        return isValid;
    }

    private void loadTable() {
        String sql = "Select * from login_table where userrole = ? ";
        DefaultTableModel dm = (DefaultTableModel) dataTable.getModel();
        Connection conn;
        try {
            conn = DBConnector.getConnection();

        } catch (SQLException ex) {
            Logger.getLogger(AddDoctor.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        int rowCount = dataTable.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dm.removeRow(0);
        }

        try {
            conn = DBConnector.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "doctor");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String fullname = rs.getString("fullname");
                String name = rs.getString("username");
                String pass = rs.getString("password");
                String gender = rs.getString("gender");
                String age = rs.getString("age");
                String contact = rs.getString("contact");
                String address = rs.getString("address");

                dm.addRow(new Object[]{fullname, name, pass, gender, age, contact, address});
                //update();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

}
