/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author munazir
 */
public class AppointList extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    List<AppointModel> appoints;
    private AppointModel appoint;
    private UserModel user;

    public AppointList() {
        initComponents();
        appoints = new ArrayList<>();
        setLocationRelativeTo(null);

    }

    AppointList(UserModel user) {
        this();
        this.user = user;
        reloadAppoinmentList();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        viewlist = new javax.swing.JButton();
        Pexit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewlist.setBackground(new java.awt.Color(153, 183, 190));
        viewlist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewlist.setText("View List");
        viewlist.setActionCommand("");
        viewlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlistActionPerformed(evt);
            }
        });
        getContentPane().add(viewlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 119, -1));

        Pexit.setBackground(new java.awt.Color(153, 183, 190));
        Pexit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logout.png"))); // NOI18N
        Pexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PexitActionPerformed(evt);
            }
        });
        getContentPane().add(Pexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 183, 190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(190, 235, 200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Appointment Patients");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 306, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 820, 70));

        adataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patinent Name", "Gender", "Age", "Contact", "Doctor Name", "Department", "Hospital", "Problem", "Date", "Status"
            }
        ));
        adataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adataTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 820, 265));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void adataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adataTableMouseClicked
        // TODO add your handling code here:

        //int selectedRow = dataTable.getSelectedRow();
        // dataTable.getValueAt(selectedRow, 0);

    }//GEN-LAST:event_adataTableMouseClicked

    private void viewlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlistActionPerformed
        // TODO add your handling code here:
       
        updateTable();
        reloadAppoinmentList();

    }//GEN-LAST:event_viewlistActionPerformed

    private void PexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PexitActionPerformed
        // TODO add your handling code here:

        dispose();
        new Doctor().setVisible(true);
    }//GEN-LAST:event_PexitActionPerformed

    // pst.setString(3, buttonGroup1.getSelection().getActionCommand());
    // pst.setString(3, "male");
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointList.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointList.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointList.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointList.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new AppointList().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pexit;
    private javax.swing.JTable adataTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewlist;
    // End of variables declaration//GEN-END:variables

    private void reloadAppoinmentList() {
        //System.out.println(user.getUsername());
        //System.out.println("munazir");

        try {
            String sql = "Select * from appoint_table where dusername = ? ";
            Connection conn = DBConnector.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            System.out.println("munazir");
           System.out.println(user.getUsername());

            pst.setString(1, user.getUsername());
           
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                String patientfName = rs.getString("patientfname");
                String pusername = rs.getString("pusername");

                String pGender = rs.getString("pgender");
                String pAge = rs.getString("page");
                String pContact = rs.getString("pcontact");
                String doctorfName = rs.getString("doctorfname");
                String dusername = rs.getString("dusername");
                String department = rs.getString("department");
                String hospital = rs.getString("hospital");
                String problem = rs.getString("problem");
                Date date = rs.getDate("date");
                String status = rs.getString("status");

                AppointModel appointment = new AppointModel(patientfName,
                        pusername,
                        pGender,
                        pAge,
                        pContact,
                        doctorfName,
                        dusername,
                        department,
                        hospital,
                        problem,
                        date,
                        status);
                appoints.add(appointment);
                //update();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    private void updateTable() {
        DefaultTableModel dm = (DefaultTableModel) adataTable.getModel();

        int rowCount = adataTable.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dm.removeRow(0);
        }

         for(AppointModel a: appoints){
          dm.addRow(a.toTableObject());
       }
    }

}
