/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example;

import javax.swing.JOptionPane;

/**
 *
 * @author munazir
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BanckGroundPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLevel = new javax.swing.JLabel();
        LoadingP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BanckGroundPanel.setBackground(new java.awt.Color(0, 125, 147));
        BanckGroundPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BanckGroundPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        BanckGroundPanel.setName(""); // NOI18N
        BanckGroundPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        BanckGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\munazir\\Desktop\\shcs\\team3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        BanckGroundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 720, 390));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("SMART HEALTH CONSULTING SYSTEM");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 740, 80));

        BanckGroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        LoadingBar.setBackground(new java.awt.Color(255, 255, 255));
        BanckGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 900, 20));

        LoadingLevel.setBackground(new java.awt.Color(255, 255, 255));
        LoadingLevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingLevel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLevel.setText("Loading.....");
        BanckGroundPanel.add(LoadingLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 200, -1));

        LoadingP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingP.setForeground(new java.awt.Color(255, 255, 255));
        LoadingP.setText("0 %");
        BanckGroundPanel.add(LoadingP, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BanckGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BanckGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       SplashScreen sp =new SplashScreen();
       sp.setVisible(true);
        try {
           
            for (int i=0;i<=100;i++){
                
               Thread.sleep(25);
               sp.LoadingP.setText(i +"%");
               if (i==10){
                
                   sp.LoadingLevel.setText("Trurning on Modules...");
              }
               if (i==20){
              
                  sp.LoadingLevel.setText("Loading   Modules...");
                  
              }
                 if (i==50){
               
                   sp.LoadingLevel.setText("Connecting  to Database...");
                  
           }
                 if (i==70){
              
               sp.LoadingLevel.setText("Connection Successful !");
                   
               }
                   if (i==80){
               
                   sp.LoadingLevel.setText("Lounching Application ....");
                 
               }
                   
                    
               
                  sp.LoadingBar.setValue(i);
                   
                         
          }
                } catch (Exception e) {
          
          JOptionPane.showMessageDialog(null,e);
          
      }
             sp.setVisible(false);
             new Login().setVisible(true);
              
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BanckGroundPanel;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLevel;
    private javax.swing.JLabel LoadingP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
